server:
  port: 8081
spring:
  application:
    name: framework
  main:
    allow-bean-definition-overriding: true
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

dubbo:
  application:
    id: framework
    name: framework
    qos-enable: false

msg:
  enable: true
  username: wangxi
  password: 123
